# Intro to Our Research
Now that we have our story for our project, how do we conduct research to find out what students want to see out of ChatGPT? 
We went out of our comfort zone and interviewed over 100 students at the Ross School of Business to gauge their insights about ChatGPT, if they use it, what they use it for, do they take into account biases, what they would like to see from ChatGPT, and more. Our group made a survey and we went around all areas at Ross and asked if they would like to take a survey for our project. Some students respectfully declined, others were happy to take it, and we unfortunately had the occasional “Yes, I will take it later.” All in all, we received 70 responses, with students from the Masters of Supply Chain Management being the program with the most respondents. Below is a graph of the programs with students who responded.

To really understand if students use ChatGPT, we asked them, and the results are eye-opening. A whopping 33 students, or 47.1% of students said they use ChatGPT “Several times a week.” Furthermore, 19 students responded with “Daily,” and 15 students responded with “Occasionally.” See the graph below for more detail.

Seeing as a majority of students surveyed use ChatGPT, it only reinforces the idea that as the leaders and best, we should take steps to utilize ChatGPT to our advantage by taking meaningful concepts from ChatGPT to apply to our lives. In the sections that follow, we will place emphasis on how students can utilize ChatGPT in terms of career planning, homework, and well-being to make their lives less stressful during their time at the Ross School of Business.

