# Our story
This marks the beginning of our project. We want you, the students of the Ross School of Business, to walk away from this website knowing more about how to effectively use ChatGPT to your advantage to “Survive your time at the Ross School of Business.” We are just like you, stressed from all the homework, group projects, family matters, extracurricular activities that we participate in. Dealing with all of this puts an enormous amount of stress onto us and we are left feeling with the thought that we will not be able to accomplish our goals and dreams during our time here at Ross. 
So, we want to help you achieve those dreams and goals by creating the “Ross Survival Kit.” The Ross Survival Kit is a best practices guide for you, the students, to effectively use and navigate ChatGPT to your advantage. We want to show you how to use ChatGPT in an easier and more effective way so that when you feel overwhelmed by the pile of homework, or career planning, or just your well being, you can use ChatGPT effectively to limit the amount of stress you have. 
Since ChatGPT’s rise of popularity over the past year, students have flocked to OpenAI to get their use out of ChatGPT. Given all a user has to do is type a prompt into the text box, why are we trying to help students achieve something they already know how to do? Because we, along with everyone else at Ross, are the leaders and best. For our project it’s simple: we strive to make things better for students, we want the students to take meaningful lessons away from ChatGPT, not just the answer, and we want to make your lives less stressful to survive your time at the Ross School of Business.
